use crate::client::Client;
use crate::commands::app::{
    collect_backend_files_for_manifest, validate_backend_contract_files,
};
use crate::config::Config;
use crate::project::Manifest;
use localapp_core::validate_database_compatibility;
use rusqlite::{Connection, params};
#[cfg(test)]
use serde_json::Value;
use serde_json::json;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
#[cfg(test)]
use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

const PLATFORM_TYPE_HINT: &str =
    "For platform data types (users, groups, roles), import from @localapp/sdk-react";

#[derive(Debug)]
pub(crate) struct ColumnInfo {
    pub name: String,
    pub sqlite_type: String,
    pub not_null: bool,
    pub primary_key: bool,
}

pub fn types(output: &str) -> Result<(), String> {
    let cwd = std::env::current_dir().map_err(|e| format!("Failed to get cwd: {e}"))?;
    let db_path = cwd.join(".localapp").join("dev.db");
    if !db_path.exists() {
        return Err("dev.db not found. Run localapp db migrate first.".to_string());
    }

    let conn = Connection::open(&db_path).map_err(|e| format!("Failed to open dev.db: {e}"))?;
    let tables = user_tables(&conn)?;
    let mut content = String::new();
    content.push_str("// Generated by localapp db types.\n");
    content.push_str("// ");
    content.push_str(PLATFORM_TYPE_HINT);
    content.push_str("\n\n");

    if tables.is_empty() {
        content.push_str("// No user tables found in dev.db. Run localapp db migrate first.\n");
    } else {
        for table in &tables {
            content.push_str(&render_interface(&conn, table)?);
            content.push('\n');
        }
    }

    let output_path = cwd.join(output);
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create output directory: {e}"))?;
    }
    fs::write(&output_path, content).map_err(|e| format!("Failed to write {output}: {e}"))?;

    if tables.is_empty() {
        println!("No user tables found in dev.db. Run localapp db migrate first.");
    } else {
        println!("Generated {} interfaces to {}", tables.len(), output);
    }
    Ok(())
}

pub fn migrate() -> Result<(), String> {
    let cwd = std::env::current_dir().map_err(|e| format!("Failed to get cwd: {e}"))?;
    let localapp_dir = cwd.join(".localapp");
    fs::create_dir_all(&localapp_dir).map_err(|e| format!("Failed to create .localapp: {e}"))?;
    let db_path = localapp_dir.join("dev.db");
    let mut conn = Connection::open(&db_path).map_err(|e| format!("Failed to open dev.db: {e}"))?;
    let applied = apply_migrations(&mut conn, &cwd.join("migrations"))?;
    if applied.is_empty() {
        println!("No pending migrations");
    } else {
        for filename in &applied {
            println!("Applied {filename}");
        }
        println!("{} migrations applied", applied.len());
    }
    Ok(())
}

pub fn reset() -> Result<(), String> {
    let cwd = std::env::current_dir().map_err(|e| format!("Failed to get cwd: {e}"))?;
    let localapp_dir = cwd.join(".localapp");
    fs::create_dir_all(&localapp_dir).map_err(|e| format!("Failed to create .localapp: {e}"))?;
    let db_path = localapp_dir.join("dev.db");
    if db_path.exists() {
        fs::remove_file(&db_path).map_err(|e| format!("Failed to remove existing dev.db: {e}"))?;
    }

    let mut conn =
        Connection::open(&db_path).map_err(|e| format!("Failed to create dev.db: {e}"))?;
    let applied = apply_migrations(&mut conn, &cwd.join("migrations"))?;
    ensure_applied_migrations_table(&conn)?;

    let migration_applied = fs::read(&db_path).ok();
    let seed_path = cwd.join("db").join("seeds").join("dev.sql");
    if seed_path.exists() {
        let sql = fs::read_to_string(&seed_path)
            .map_err(|e| format!("Failed to read db/seeds/dev.sql: {e}"))?;
        let count = count_sql_statements(&sql);
        let tx = conn
            .transaction()
            .map_err(|e| format!("Failed to start seed transaction: {e}"))?;
        if let Err(error) = tx.execute_batch(&sql) {
            drop(tx);
            drop(conn);
            if let Some(bytes) = migration_applied {
                fs::write(&db_path, bytes)
                    .map_err(|e| format!("Failed to restore dev.db after seed failure: {e}"))?;
            }
            return Err(format!(
                "Seed failed. dev.db rolled back to migration-applied state. {error}"
            ));
        }
        tx.commit()
            .map_err(|e| format!("Failed to commit seed: {e}"))?;
        println!("Applied seed: {count} SQL statements");
    } else {
        println!("No seed file found at db/seeds/dev.sql");
    }

    println!("Applied {} migrations", applied.len());
    Ok(())
}

pub async fn validate() -> Result<(), String> {
    validate_with_output(true).await
}

async fn validate_with_output(verbose: bool) -> Result<(), String> {
    let config = Config::load().ok_or("Not configured. Run 'localapp login' first.")?;
    validate_with_output_and_config(verbose, &config).await
}

pub async fn validate_silent_with_config(config: &Config) -> Result<(), String> {
    validate_with_output_and_config(false, config).await
}

async fn validate_with_output_and_config(verbose: bool, config: &Config) -> Result<(), String> {
    let cwd = std::env::current_dir().map_err(|e| format!("Failed to get cwd: {e}"))?;
    let manifest =
        Manifest::read(&cwd).ok_or("No manifest.json found. Run 'localapp init' first.")?;
    let backend_files = collect_backend_files_for_manifest(&cwd, &manifest)?;
    validate_backend_contract_files(&backend_files)?;
    let client = Client::new(config);

    let localapp_dir = cwd.join(".localapp");
    fs::create_dir_all(&localapp_dir).map_err(|e| format!("Failed to create .localapp: {e}"))?;
    let snapshot_path = localapp_dir.join("prod-snapshot.db");
    let marker_path = localapp_dir.join(".last-validated");

    let (status, bytes) = client
        .get_bytes(&format!("/api/db/snapshot?name={}", manifest.name))
        .await?;
    let snapshot = if status == 404 {
        Vec::new()
    } else if status != 200 {
        return Err("Cannot reach prod server. Validation requires online connection.".to_string());
    } else {
        bytes
    };
    fs::write(&snapshot_path, &snapshot)
        .map_err(|e| format!("Failed to write prod-snapshot.db: {e}"))?;
    let checksums = migration_checksums(&cwd.join("migrations"))?;
    let applied =
        match validate_database_compatibility(&snapshot, &cwd.join("migrations"), &backend_files) {
            Ok(applied) => applied,
            Err(error) => {
                let _ = fs::remove_file(&marker_path);
                return Err(format!("Validation FAILED: {error}"));
            }
        };

    fs::write(
        &marker_path,
        serde_json::to_string_pretty(&json!({
            "validatedAt": now_unix_seconds(),
            "checksums": checksums,
            "backendChecksums": backend_file_checksums(&backend_files),
        }))
        .unwrap_or_default(),
    )
    .map_err(|e| format!("Failed to write .last-validated: {e}"))?;

    if verbose {
        println!("Validate OK. {} migrations ready to apply.", applied.len());
    }
    Ok(())
}

pub fn validate_local_migrations(project_dir: &Path) -> Result<(), String> {
    validate_fresh_migration_chain(&project_dir.join("migrations"))
}

pub fn status() -> Result<(), String> {
    let cwd = std::env::current_dir().map_err(|e| format!("Failed to get cwd: {e}"))?;
    let db_path = cwd.join(".localapp").join("dev.db");
    let migration_files = read_migration_files(&cwd.join("migrations"))?;
    let mut applied = BTreeMap::new();

    if db_path.exists() {
        let conn = Connection::open(&db_path).map_err(|e| format!("Failed to open dev.db: {e}"))?;
        ensure_applied_migrations_table(&conn)?;
        let mut stmt = conn
            .prepare("SELECT filename, checksum, applied_at FROM _localapp_applied_migrations ORDER BY filename")
            .map_err(|e| format!("Failed to query applied migrations: {e}"))?;
        let rows = stmt
            .query_map([], |row| {
                Ok((
                    row.get::<_, String>(0)?,
                    row.get::<_, String>(1)?,
                    row.get::<_, String>(2)?,
                ))
            })
            .map_err(|e| format!("Failed to read applied migrations: {e}"))?;
        for row in rows {
            let (filename, checksum, applied_at) =
                row.map_err(|e| format!("Failed to read migration row: {e}"))?;
            applied.insert(filename, (checksum, applied_at));
        }
    }

    println!("Applied migrations");
    if applied.is_empty() {
        println!("  (none)");
    } else {
        for (filename, (checksum, applied_at)) in &applied {
            println!("  {filename} {checksum} {applied_at}");
        }
    }

    println!("Pending migrations");
    let mut pending_count = 0;
    for path in migration_files {
        let filename = filename_for_path(&path)?;
        if !applied.contains_key(&filename) {
            println!("  {filename}");
            pending_count += 1;
        }
    }
    if pending_count == 0 {
        println!("  (none)");
    }
    Ok(())
}

pub async fn restore(
    backup: &str,
    i_know_this_loses_data: bool,
    confirm_project_name: Option<&str>,
) -> Result<(), String> {
    let cwd = std::env::current_dir().map_err(|e| format!("Failed to get cwd: {e}"))?;
    let manifest =
        Manifest::read(&cwd).ok_or("No manifest.json found. Run 'localapp init' first.")?;
    if !i_know_this_loses_data || confirm_project_name != Some(manifest.name.as_str()) {
        return Err(format!(
            "Restoring a database backup loses current production data. Add --i-know-this-loses-data --confirm-project-name {} to proceed.",
            manifest.name
        ));
    }
    let config = Config::load().ok_or("Not configured. Run 'localapp login' first.")?;
    let client = Client::new(&config);
    let (status, body) = client
        .post_json(
            "/api/db/restore",
            json!({ "name": manifest.name, "backup": backup }),
        )
        .await?;
    if status != 200 || !body["success"].as_bool().unwrap_or(false) {
        return Err(body["error"]
            .as_str()
            .unwrap_or("Restore failed")
            .to_string());
    }
    println!("Restore complete from backup {backup}");
    Ok(())
}

pub fn shell(snapshot: bool, command: Option<&str>) -> Result<(), String> {
    let cwd = std::env::current_dir().map_err(|e| format!("Failed to get cwd: {e}"))?;
    let db_path = if snapshot {
        cwd.join(".localapp").join("prod-snapshot.db")
    } else {
        cwd.join(".localapp").join("dev.db")
    };
    if snapshot && !db_path.exists() {
        return Err("No prod snapshot found. Run 'localapp db validate' first.".to_string());
    }
    if !snapshot && !db_path.exists() {
        return Err(
            "No dev.db found. Run 'localapp db migrate' or 'localapp db reset' first.".to_string(),
        );
    }

    let mut cmd = Command::new("sqlite3");
    cmd.arg(&db_path);
    if let Some(command) = command {
        cmd.arg(command);
    }
    let status = cmd.status().map_err(|_| {
        "sqlite3 command not found. Install it or use localapp db types to inspect schema."
            .to_string()
    })?;
    if !status.success() {
        return Err(format!("sqlite3 exited with status {status}"));
    }
    Ok(())
}

pub fn has_recent_validation(cwd: &Path) -> Result<bool, String> {
    let marker_path = cwd.join(".localapp").join(".last-validated");
    if !marker_path.exists() {
        return Ok(false);
    }
    let marker: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(&marker_path)
            .map_err(|e| format!("Failed to read .last-validated: {e}"))?,
    )
    .map_err(|e| format!("Invalid .last-validated: {e}"))?;
    let validated_at = marker["validatedAt"].as_u64().unwrap_or(0);
    if now_unix_seconds().saturating_sub(validated_at) > 3600 {
        return Ok(false);
    }
    let current = migration_checksums(&cwd.join("migrations"))?;
    let saved = marker["checksums"].as_object().cloned().unwrap_or_default();
    if saved.len() != current.len() {
        return Ok(false);
    }
    for (filename, checksum) in current {
        if saved.get(&filename).and_then(|value| value.as_str()) != Some(checksum.as_str()) {
            return Ok(false);
        }
    }
    let manifest =
        Manifest::read(&cwd).ok_or("No manifest.json found. Run 'localapp init' first.")?;
    let backend_files = collect_backend_files_for_manifest(&cwd, &manifest)?;
    let current_backend = backend_file_checksums(&backend_files);
    let saved_backend = marker["backendChecksums"]
        .as_object()
        .cloned()
        .unwrap_or_default();
    if saved_backend.len() != current_backend.len() {
        return Ok(false);
    }
    for (filename, checksum) in current_backend {
        if saved_backend
            .get(&filename)
            .and_then(|value| value.as_str())
            != Some(checksum.as_str())
        {
            return Ok(false);
        }
    }
    Ok(true)
}

pub(crate) fn user_tables(conn: &Connection) -> Result<Vec<String>, String> {
    let mut stmt = conn
        .prepare("SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name")
        .map_err(|e| format!("Failed to query tables: {e}"))?;
    let rows = stmt
        .query_map([], |row| row.get::<_, String>(0))
        .map_err(|e| format!("Failed to read tables: {e}"))?;

    let mut tables = Vec::new();
    for row in rows {
        let table = row.map_err(|e| format!("Failed to read table name: {e}"))?;
        if table.starts_with("_localapp_")
            || table.starts_with("sqlite_")
            || matches!(table.as_str(), "users" | "groups" | "roles")
        {
            continue;
        }
        tables.push(table);
    }
    Ok(tables)
}

fn render_interface(conn: &Connection, table: &str) -> Result<String, String> {
    let columns = table_columns(conn, table)?;
    let mut out = format!("export interface {table} {{\n");
    for column in columns {
        let optional = if column.not_null || column.primary_key {
            ""
        } else {
            "?"
        };
        if column.name.ends_with("_at") {
            out.push_str("  /** ISO 8601 timestamp */\n");
        }
        out.push_str(&format!(
            "  {}{}: {};\n",
            column.name,
            optional,
            ts_type_for_column(&column),
        ));
    }
    out.push_str("}\n");
    Ok(out)
}

pub(crate) fn table_columns(conn: &Connection, table: &str) -> Result<Vec<ColumnInfo>, String> {
    let escaped = table.replace('"', "\"\"");
    let mut stmt = conn
        .prepare(&format!("PRAGMA table_info(\"{escaped}\")"))
        .map_err(|e| format!("Failed to inspect table {table}: {e}"))?;
    let rows = stmt
        .query_map([], |row| {
            Ok(ColumnInfo {
                name: row.get(1)?,
                sqlite_type: row.get::<_, String>(2)?,
                not_null: row.get::<_, i64>(3)? != 0,
                primary_key: row.get::<_, i64>(5)? != 0,
            })
        })
        .map_err(|e| format!("Failed to read columns for {table}: {e}"))?;

    let mut columns = Vec::new();
    for row in rows {
        columns.push(row.map_err(|e| format!("Failed to read column for {table}: {e}"))?);
    }
    Ok(columns)
}

#[cfg(test)]
fn validate_backend_schema_matches_db(
    conn: &Connection,
    backend_files: &[(String, Vec<u8>)],
) -> Result<(), String> {
    for (path, data) in backend_files {
        if !path.ends_with("schema.json") {
            continue;
        }
        let value: serde_json::Value = serde_json::from_slice(data)
            .map_err(|e| format!("Invalid backend JSON {path}: {e}"))?;
        if value.get("$schema").and_then(|schema| schema.as_str())
            != Some("https://localapp.dev/schemas/backend/resource-schema.schema.json")
        {
            continue;
        }
        let Some(name) = value.get("name").and_then(|name| name.as_str()) else {
            continue;
        };
        let tables = user_tables(conn)?;
        if !tables.iter().any(|table| table == name) {
            return Err(format!(
                "Backend schema {name} has no matching migration table"
            ));
        }
        let db_fields = table_columns(conn, name)?
            .into_iter()
            .map(|column| column.name)
            .collect::<HashSet<_>>();
        if let Some(schema_fields) = value.get("fields").and_then(|fields| fields.as_object()) {
            for field in schema_fields.keys() {
                if !db_fields.contains(field) {
                    return Err(format!(
                        "Backend schema {name}.{field} does not match migrations: column not found"
                    ));
                }
            }
        }
        validate_business_field_references(name, value.get("business"), &db_fields)?;
    }
    Ok(())
}

#[cfg(test)]
fn validate_business_field_references(
    resource_name: &str,
    business: Option<&Value>,
    db_fields: &HashSet<String>,
) -> Result<(), String> {
    let Some(business) = business.and_then(|value| value.as_object()) else {
        return Ok(());
    };

    for key in ["ownerField", "statusField"] {
        if let Some(field) = business.get(key).and_then(|value| value.as_str()) {
            if !db_fields.contains(field) {
                return Err(format!(
                    "Backend schema {resource_name}.business.{key} references missing migration column: {field}"
                ));
            }
        }
    }

    for key in ["defaultFields", "enums"] {
        if let Some(fields) = business.get(key).and_then(|value| value.as_object()) {
            for field in fields.keys() {
                if !db_fields.contains(field) {
                    return Err(format!(
                        "Backend schema {resource_name}.business.{key}.{field} references missing migration column"
                    ));
                }
            }
        }
    }

    Ok(())
}

fn ts_type_for_column(column: &ColumnInfo) -> &'static str {
    let upper = column.sqlite_type.to_uppercase();
    if column.name.starts_with("is_") {
        return "boolean";
    }
    if upper.contains("BLOB") {
        return "Uint8Array";
    }
    if upper.contains("INT")
        || upper.contains("REAL")
        || upper.contains("NUM")
        || upper.contains("DOUBLE")
        || upper.contains("FLOAT")
    {
        return "number";
    }
    "string"
}

pub(crate) fn apply_migrations(
    conn: &mut Connection,
    migrations_dir: &Path,
) -> Result<Vec<String>, String> {
    ensure_applied_migrations_table(conn)?;
    let migrations = read_migration_files(migrations_dir)?;
    let applied_checksums = applied_migration_checksums(conn)?;
    let mut applied_now = Vec::new();
    for migration in &migrations {
        let filename = filename_for_path(migration)?;
        let sql = fs::read_to_string(migration)
            .map_err(|e| format!("Failed to read migration {}: {e}", migration.display()))?;
        let checksum = checksum_text(&sql);
        if let Some(applied_checksum) = applied_checksums.get(&filename) {
            if applied_checksum == &checksum {
                continue;
            }
            return Err(format!(
                "Migration {filename} was modified after being applied. Restore the original file or create a new migration."
            ));
        }
        conn.execute_batch(&sql)
            .map_err(|e| format!("Failed to apply migration {}: {e}", migration.display()))?;
        conn.execute(
            "INSERT OR REPLACE INTO _localapp_applied_migrations (filename, checksum, applied_at) VALUES (?1, ?2, datetime('now'))",
            params![filename, checksum],
        )
        .map_err(|e| format!("Failed to record migration {filename}: {e}"))?;
        applied_now.push(filename);
    }
    Ok(applied_now)
}

fn validate_fresh_migration_chain(migrations_dir: &Path) -> Result<(), String> {
    let mut conn = Connection::open_in_memory().map_err(|e| {
        format!("Failed to open in-memory SQLite for fresh migration validation: {e}")
    })?;
    apply_migrations(&mut conn, migrations_dir)
        .map(|_| ())
        .map_err(|error| format!("Fresh migration Validation FAILED: {error}"))
}

#[cfg(test)]
fn validate_local_migrations_include_applied(
    conn: &Connection,
    local_checksums: &BTreeMap<String, String>,
) -> Result<(), String> {
    ensure_applied_migrations_table(conn)?;
    let applied = applied_migration_checksums(conn)?;
    for (filename, checksum) in applied {
        let Some(local_checksum) = local_checksums.get(&filename) else {
            return Err(format!(
                "Migration {filename} has already been applied in production but is missing locally. Restore the migration file instead of deleting it."
            ));
        };
        if local_checksum != &checksum {
            return Err(format!(
                "Migration {filename} has already been applied in production with a different checksum. Restore the original file or create a new migration."
            ));
        }
    }
    Ok(())
}

fn ensure_applied_migrations_table(conn: &Connection) -> Result<(), String> {
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS _localapp_applied_migrations (
          filename TEXT PRIMARY KEY,
          checksum TEXT NOT NULL,
          applied_at TEXT NOT NULL
        );",
    )
    .map_err(|e| format!("Failed to create migrations table: {e}"))
}

fn read_migration_files(migrations_dir: &Path) -> Result<Vec<PathBuf>, String> {
    if !migrations_dir.exists() {
        return Ok(Vec::new());
    }
    let mut files = fs::read_dir(migrations_dir)
        .map_err(|e| format!("Failed to read migrations directory: {e}"))?
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("sql"))
        .collect::<Vec<_>>();
    files.sort();
    Ok(files)
}

fn applied_migration_checksums(conn: &Connection) -> Result<BTreeMap<String, String>, String> {
    let mut stmt = conn
        .prepare("SELECT filename, checksum FROM _localapp_applied_migrations")
        .map_err(|e| format!("Failed to query applied migrations: {e}"))?;
    let rows = stmt
        .query_map([], |row| {
            Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
        })
        .map_err(|e| format!("Failed to read applied migrations: {e}"))?;
    let mut checksums = BTreeMap::new();
    for row in rows {
        let (filename, checksum) = row.map_err(|e| format!("Failed to read migration row: {e}"))?;
        checksums.insert(filename, checksum);
    }
    Ok(checksums)
}

fn count_sql_statements(sql: &str) -> usize {
    sql.split(';')
        .filter(|stmt| !stmt.trim().is_empty())
        .count()
}

fn migration_checksums(migrations_dir: &Path) -> Result<BTreeMap<String, String>, String> {
    let mut checksums = BTreeMap::new();
    for path in read_migration_files(migrations_dir)? {
        let filename = filename_for_path(&path)?;
        let sql = fs::read_to_string(&path)
            .map_err(|e| format!("Failed to read migration {}: {e}", path.display()))?;
        checksums.insert(filename, checksum_text(&sql));
    }
    Ok(checksums)
}

fn backend_file_checksums(files: &[(String, Vec<u8>)]) -> BTreeMap<String, String> {
    files
        .iter()
        .map(|(filename, data)| (filename.clone(), format!("{:x}", Sha256::digest(data))))
        .collect()
}

fn filename_for_path(path: &Path) -> Result<String, String> {
    path.file_name()
        .and_then(|name| name.to_str())
        .map(|name| name.to_string())
        .ok_or_else(|| format!("Invalid migration filename: {}", path.display()))
}

fn checksum_text(text: &str) -> String {
    format!("{:x}", Sha256::digest(text.as_bytes()))
}

fn now_unix_seconds() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::{
        checksum_text, validate_backend_schema_matches_db, validate_fresh_migration_chain,
        validate_local_migrations_include_applied,
    };
    use rusqlite::Connection;
    use rusqlite::params;
    use std::fs;
    use std::path::PathBuf;

    #[test]
    fn rejects_backend_schema_that_does_not_match_migrated_table() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch("CREATE TABLE work_items (id INTEGER PRIMARY KEY, title TEXT);")
            .unwrap();
        let backend_files = vec![(
            "backend/resources/work_items/schema.json".to_string(),
            br#"{
          "$schema": "https://localapp.dev/schemas/backend/resource-schema.schema.json",
          "name": "work_items",
          "fields": {
            "id": { "type": "auto_increment" },
            "title": { "type": "string" },
            "ghost": { "type": "string" }
          }
        }"#
            .to_vec(),
        )];

        let error = validate_backend_schema_matches_db(&conn, &backend_files).unwrap_err();
        assert!(error.contains("work_items.ghost"));
        assert!(error.contains("migrations"));
    }

    #[test]
    fn allows_backend_schema_to_declare_only_business_metadata() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(
            "CREATE TABLE work_items (
                id INTEGER PRIMARY KEY,
                title TEXT NOT NULL,
                status TEXT,
                created_by_member_id INTEGER
            );",
        )
        .unwrap();
        let backend_files = vec![(
            "backend/resources/work_items/schema.json".to_string(),
            br#"{
          "$schema": "https://localapp.dev/schemas/backend/resource-schema.schema.json",
          "name": "work_items",
          "business": {
            "ownerField": "created_by_member_id",
            "statusField": "status",
            "defaultFields": {
              "created_by_member_id": { "defaultFrom": "currentUser.id" }
            },
            "enums": {
              "status": ["todo", "doing", "done"]
            }
          }
        }"#
            .to_vec(),
        )];

        validate_backend_schema_matches_db(&conn, &backend_files).unwrap();
    }

    #[test]
    fn ignores_backend_action_files_when_matching_schema_to_db() {
        let conn = Connection::open_in_memory().unwrap();
        let backend_files = vec![
            (
                "backend/actions.manifest.json".to_string(),
                br#"{"version":1,"actions":[]}"#.to_vec(),
            ),
            (
                "backend/actions.bundle.mjs".to_string(),
                b"export const action = {};".to_vec(),
            ),
        ];

        validate_backend_schema_matches_db(&conn, &backend_files).unwrap();
    }

    #[test]
    fn rejects_business_metadata_that_references_missing_migration_column() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch("CREATE TABLE work_items (id INTEGER PRIMARY KEY, title TEXT);")
            .unwrap();
        let backend_files = vec![(
            "backend/resources/work_items/schema.json".to_string(),
            br#"{
          "$schema": "https://localapp.dev/schemas/backend/resource-schema.schema.json",
          "name": "work_items",
          "business": {
            "ownerField": "created_by_member_id"
          }
        }"#
            .to_vec(),
        )];

        let error = validate_backend_schema_matches_db(&conn, &backend_files).unwrap_err();
        assert!(error.contains("business.ownerField"));
        assert!(error.contains("created_by_member_id"));
    }

    #[test]
    fn rejects_fresh_migration_chain_with_duplicate_column() {
        let tmp = tempdir();
        let migrations_dir = tmp.path.join("migrations");
        fs::create_dir_all(&migrations_dir).unwrap();
        fs::write(
            migrations_dir.join("001_init.sql"),
            "CREATE TABLE todos (id INTEGER PRIMARY KEY, source TEXT);",
        )
        .unwrap();
        fs::write(
            migrations_dir.join("003_add_source.sql"),
            "ALTER TABLE todos ADD COLUMN source TEXT;",
        )
        .unwrap();

        let error = validate_fresh_migration_chain(&migrations_dir).unwrap_err();

        assert!(error.contains("Fresh migration Validation FAILED"));
        assert!(error.contains("duplicate column"));
    }

    #[test]
    fn rejects_deleted_migration_that_was_already_applied_in_prod_snapshot() {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(
            "CREATE TABLE _localapp_applied_migrations (
              filename TEXT PRIMARY KEY,
              checksum TEXT NOT NULL,
              applied_at TEXT NOT NULL
            );",
        )
        .unwrap();
        conn.execute(
            "INSERT INTO _localapp_applied_migrations (filename, checksum, applied_at) VALUES (?1, ?2, datetime('now'))",
            params!["001_init.sql", checksum_text("CREATE TABLE todos (id INTEGER);")],
        ).unwrap();
        let local_checksums = std::collections::BTreeMap::new();

        let error = validate_local_migrations_include_applied(&conn, &local_checksums).unwrap_err();

        assert!(error.contains("001_init.sql"));
        assert!(error.contains("missing locally"));
    }

    fn tempdir() -> TempDir {
        let mut path = std::env::temp_dir();
        let id = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        path.push(format!("localapp-db-test-{}", id));
        std::fs::create_dir_all(&path).unwrap();
        TempDir { path }
    }

    struct TempDir {
        path: PathBuf,
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.path);
        }
    }
}
