use serde_json::{Map, Value};
use std::fs;

pub fn run() -> Result<(), String> {
    let cwd = std::env::current_dir().map_err(|e| format!("Failed to get cwd: {e}"))?;
    let manifest_path = cwd.join("manifest.json");
    if !manifest_path.exists() {
        return Err("No manifest.json found. Run 'localapp init' first.".to_string());
    }

    let content = fs::read_to_string(&manifest_path)
        .map_err(|e| format!("Failed to read manifest.json: {e}"))?;
    let mut manifest: Value =
        serde_json::from_str(&content).map_err(|e| format!("Invalid manifest.json: {e}"))?;
    let Some(schemas) = manifest.get("schemas").cloned() else {
        println!("No manifest.schemas found. Nothing to migrate.");
        return Ok(());
    };
    if schemas.as_object().is_none_or(|schemas| schemas.is_empty()) {
        println!("No manifest.schemas found. Nothing to migrate.");
        return Ok(());
    }

    let migrations_dir = cwd.join("migrations");
    if migrations_dir.exists() {
        return Err("migrations directory already exists. Move it aside before running migrate-from-manifest.".to_string());
    }

    let sql = render_migration(&schemas)?;
    fs::create_dir_all(&migrations_dir)
        .map_err(|e| format!("Failed to create migrations directory: {e}"))?;
    fs::write(migrations_dir.join("001_initial_from_manifest.sql"), sql)
        .map_err(|e| format!("Failed to write migration: {e}"))?;
    fs::write(cwd.join("manifest.json.bak"), content)
        .map_err(|e| format!("Failed to write manifest.json.bak: {e}"))?;
    if let Some(obj) = manifest.as_object_mut() {
        preserve_business_metadata(obj, &schemas);
        obj.remove("schemas");
    }
    fs::write(
        &manifest_path,
        serde_json::to_string_pretty(&manifest).unwrap_or_default(),
    )
    .map_err(|e| format!("Failed to write manifest.json: {e}"))?;

    println!("Generated migrations/001_initial_from_manifest.sql");
    println!("Backed up manifest.json to manifest.json.bak and removed schemas field.");
    Ok(())
}

fn preserve_business_metadata(manifest: &mut Map<String, Value>, schemas: &Value) {
    let Some(schemas) = schemas.as_object() else {
        return;
    };
    let business_entry = manifest
        .entry("business".to_string())
        .or_insert_with(|| Value::Object(Map::new()));
    let Some(business) = business_entry.as_object_mut() else {
        return;
    };

    for (table_name, schema) in schemas {
        let mut table_business = business
            .get(table_name)
            .and_then(Value::as_object)
            .cloned()
            .unwrap_or_default();

        if let Some(schema_business) = schema.get("business").and_then(Value::as_object) {
            for (key, value) in schema_business {
                table_business.insert(key.clone(), value.clone());
            }
        }
        if let Some(route_access) = schema.get("routeAccess") {
            table_business.insert("routeAccess".to_string(), route_access.clone());
        }
        if !table_business.is_empty() {
            business.insert(table_name.clone(), Value::Object(table_business));
        }
    }
}

fn render_migration(schemas: &Value) -> Result<String, String> {
    let schemas = schemas
        .as_object()
        .ok_or("manifest.schemas must be an object keyed by table name")?;
    let mut out = String::new();
    out.push_str("-- Generated by localapp migrate-from-manifest.\n\n");
    for (table_name, schema) in schemas {
        validate_identifier(table_name)?;
        let fields = schema
            .get("fields")
            .and_then(Value::as_object)
            .ok_or_else(|| format!("Schema {table_name} is missing fields"))?;
        out.push_str(&render_create_table(table_name, fields)?);
        out.push('\n');
    }
    Ok(out)
}

fn render_create_table(table_name: &str, fields: &Map<String, Value>) -> Result<String, String> {
    let mut columns = Vec::new();
    if !fields.contains_key("id") {
        columns.push("  id INTEGER PRIMARY KEY AUTOINCREMENT".to_string());
    }
    for (field_name, field) in fields {
        validate_identifier(field_name)?;
        columns.push(render_column(field_name, field)?);
    }
    if !fields.contains_key("created_at") {
        columns.push("  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP".to_string());
    }
    if !fields.contains_key("updated_at") {
        columns.push("  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP".to_string());
    }
    Ok(format!(
        "CREATE TABLE {table_name} (\n{}\n);\n",
        columns.join(",\n")
    ))
}

fn render_column(field_name: &str, field: &Value) -> Result<String, String> {
    let field_type = field
        .get("type")
        .and_then(Value::as_str)
        .ok_or_else(|| format!("Field {field_name} is missing type"))?;
    let constraints = field.get("constraints").unwrap_or(&Value::Null);
    let sqlite_type = match field_type {
        "string" | "timestamp" => "TEXT",
        "number" => "REAL",
        "boolean" => "INTEGER",
        "auto_increment" => "INTEGER PRIMARY KEY AUTOINCREMENT",
        other => return Err(format!("Unsupported schema field type: {other}")),
    };
    let mut column = format!("  {field_name} {sqlite_type}");
    if field_type != "auto_increment" {
        if constraints
            .get("required")
            .and_then(Value::as_bool)
            .unwrap_or(false)
        {
            column.push_str(" NOT NULL");
        }
        if constraints
            .get("unique")
            .and_then(Value::as_bool)
            .unwrap_or(false)
        {
            column.push_str(" UNIQUE");
        }
        if let Some(default_value) = constraints.get("defaultValue") {
            column.push_str(" DEFAULT ");
            column.push_str(&render_default(default_value));
        }
    }
    Ok(column)
}

fn render_default(value: &Value) -> String {
    match value {
        Value::Bool(value) => {
            if *value {
                "1".to_string()
            } else {
                "0".to_string()
            }
        }
        Value::Number(value) => value.to_string(),
        Value::String(value) => format!("'{}'", value.replace('\'', "''")),
        _ => "NULL".to_string(),
    }
}

fn validate_identifier(identifier: &str) -> Result<(), String> {
    let valid = !identifier.is_empty()
        && identifier
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_')
        && identifier
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_');
    if valid {
        Ok(())
    } else {
        Err(format!("Invalid SQL identifier: {identifier}"))
    }
}
