packages:
  - "packages/localapp"
  - "packages/server"
  - "packages/server-core"
  - "packages/backend"
  - "packages/sdk-core"
  - "packages/sdk-react"
  - "packages/sdk-agent"
  - "packages/crdt"
  - "packages/web"
  - "init-repo"
  - "init-repo/runtime"
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: true
  sharp: true
