#[path = "../build_support/version_bump.rs"]
mod version_bump;

use std::fs;
use version_bump::{BuildKind, build_kind_from_profile, bump_cli_version, bump_semver};

#[test]
fn debug_build_bumps_patch_version() {
    assert_eq!(bump_semver("1.2.3", BuildKind::Debug).unwrap(), "1.2.4");
}

#[test]
fn release_build_bumps_minor_and_resets_patch() {
    assert_eq!(bump_semver("1.2.3", BuildKind::Release).unwrap(), "1.3.0");
}

#[test]
fn non_release_profiles_are_debug_bumps() {
    assert_eq!(build_kind_from_profile("debug"), BuildKind::Debug);
    assert_eq!(build_kind_from_profile("test"), BuildKind::Debug);
    assert_eq!(build_kind_from_profile("release"), BuildKind::Release);
}

#[test]
fn bump_cli_version_updates_manifest_and_lockfile() {
    let tmp = tempfile::tempdir().unwrap();
    let cargo_toml = tmp.path().join("Cargo.toml");
    let cargo_lock = tmp.path().join("Cargo.lock");
    fs::write(
        &cargo_toml,
        "[package]\nname = \"localapp\"\nversion = \"0.1.9\"\nedition = \"2024\"\n",
    )
    .unwrap();
    fs::write(
        &cargo_lock,
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"localapp\"\nversion = \"0.1.9\"\n\n[[package]]\nname = \"other\"\nversion = \"9.9.9\"\n",
    )
    .unwrap();

    let bump = bump_cli_version(&cargo_toml, &cargo_lock, BuildKind::Release).unwrap();

    assert_eq!(bump.previous, "0.1.9");
    assert_eq!(bump.next, "0.2.0");
    assert!(
        fs::read_to_string(&cargo_toml)
            .unwrap()
            .contains("version = \"0.2.0\"")
    );
    let lock = fs::read_to_string(&cargo_lock).unwrap();
    assert!(lock.contains("name = \"localapp\"\nversion = \"0.2.0\""));
    assert!(lock.contains("name = \"other\"\nversion = \"9.9.9\""));
}
